Fix/joselu/diagrama casos de uso
TheMoys/24-25-IdSw1-SDR pull request #52
Opened 2024-11-29 06:06 UTC by JLRG806

2024-11-29 16:46 UTC, TheMoys requested changes
La auditoría no se crea por un usuario, el sistema es el que las registra mediante cada acción que realiza alguien dentro del sistema, el administrador lo que tendría que poder hacer es consultarlas y descargar el informe.

2024-11-30 15:58 UTC, JLRG806 commented
Se adapto el caso de uso

2024-12-02 07:56 UTC, TheMoys requested changes
El actor "usuario" no puede hacer auditorías, unicamente el administrador.

2024-12-03 12:27 UTC, JLRG806 commented
Se arreglo el diagrama.

2024-12-04 10:18 UTC, merged